### ISSUE TITLE
fileHeader: headerAnnotation: message: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by Kur0x** [OBKoro1/koro1FileHeader#460]
### 描述bug(必填)
无法生成注释

**注释设置(必填):**

VsCode设置：

```js
    "fileheader.configObj": {
        "showErrorMessage": true,
        "writeLog": true,
    },
    "fileheader.customMade": {
        "Date": "Do not edit",
    }
```

### 文件后缀(必填):

test.ts

#### 错误日志(选填):

fileHeader: headerAnnotation: message: Cannot read properties of undefined (reading 'replace')
stack: TypeError: Cannot read properties of undefined (reading 'replace')
	at newlineAddAnnotationFn (/Users/kuro/.vscode/extensions/obkoro1.korofileheader-4.8.22/src/languageOutPut/languageOutput.js:271:21)
	at /Users/kuro/.vscode/extensions/obkoro1.korofileheader-4.8.22/src/languageOutPut/languageOutput.js:24:14
	at Array.forEach (<anonymous>)
	at middleTpl (/Users/kuro/.vscode/extensions/obkoro1.korofileheader-4.8.22/src/languageOutPut/languageOutput.js:19:21)
	at Object.headNotes (/Users/kuro/.vscode/extensions/obkoro1.korofileheader-4.8.22/src/languageOutPut/languageOutput.js:40:17)
	at /Users/kuro/.vscode/extensions/obkoro1.korofileheader-4.8.22/src/models/createAnnotation.js:39:34
	at Object.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:50207)
	at Object.headerAnnotation (/Users/kuro/.vscode/extensions/obkoro1.korofileheader-4.8.22/src/models/createAnnotation.js:30:10)
	at /Users/kuro/.vscode/extensions/obkoro1.korofileheader-4.8.22/src/main.js:22:24
	at m._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:30760)
	at m.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:31302)
	at i._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13826)
	at i._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13510)
	at i._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:12171)
	at i._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:10841)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:8947
	at u.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:34275
	at u.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
	at o._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:23615)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:21149
	at u.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at v.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:15865)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:14995
	at Socket.P (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:13797)
	at Socket.emit (node:events:390:28)
	at Socket.emit (node:domain:475:12)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
fileHeader: headerAnnotation: message: Cannot read properties of undefined (reading 'indexOf')
stack: TypeError: Cannot read properties of undefined (reading 'indexOf')
	at Object.replaceSymbolStr (/Users/kuro/.vscode/extensions/obkoro1.korofileheader-4.8.22/src/utile/util.js:246:24)
	at Object.handleTplFn (/Users/kuro/.vscode/extensions/obkoro1.korofileheader-4.8.22/src/models/handleTpl.js:25:21)
	at /Users/kuro/.vscode/extensions/obkoro1.korofileheader-4.8.22/src/models/createAnnotation.js:41:45
	at Object.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:50207)
	at Object.headerAnnotation (/Users/kuro/.vscode/extensions/obkoro1.korofileheader-4.8.22/src/models/createAnnotation.js:30:10)
	at /Users/kuro/.vscode/extensions/obkoro1.korofileheader-4.8.22/src/main.js:22:24
	at m._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:30760)
	at m.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:31302)
	at i._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13826)
	at i._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13510)
	at i._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:12171)
	at i._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:10841)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:8947
	at u.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:34275
	at u.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
	at o._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:23615)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:21149
	at u.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at v.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:15865)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:14995
	at Socket.P (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:13797)
	at Socket.emit (node:events:390:28)
	at Socket.emit (node:domain:475:12)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)

**Comment by Kur0x** [comment]
4.8.22版才有这个问题

**Comment by OBKoro1** [comment]
hi  这个问题已经修复完毕，更新插件到`v4.8.23`即可，感谢issue

**Comment by KumaYuriPool** [comment]
我最新版本也出现了，4.9.3
