### ISSUE TITLE
Mac调用函数注释快捷键报错

### ISSUE THREAD

**Issue by chf041** [OBKoro1/koro1FileHeader#562]
### 描述bug(必填)
一个清楚而简洁的bug描述。

Mac 中调用函数注释快捷键报错

VsCode设置：
{
    "go.lintOnSave": "off",
    "go.useLanguageServer": true,
    "fileheader.configObj": {
        "createFileTime": true,
        "language": {
            "languagetest": {
                "head": "/$$",
                "middle": " $ @",
                "end": " $/",
                "functionSymbol": {
                    "head": "/** ",
                    "middle": " * @",
                    "end": " */"
                },
                "functionParams": "js"
            }
        },
        "autoAdd": true,
        "autoAddLine": 100,
        "autoAlready": true,
        "annotationStr": {
            "head": "/*",
            "middle": " * @",
            "end": " */",
            "use": false
        },
        "headInsertLine": {
            "php": 2,
            "sh": 2
        },
        "beforeAnnotation": {
            "文件后缀": "该文件后缀的头部注释之前添加某些内容"
        },
        "afterAnnotation": {
            "文件后缀": "该文件后缀的头部注释之后添加某些内容"
        },
        "specialOptions": {
            "特殊字段": "自定义比如LastEditTime/LastEditors"
        },
        "switch": {
            "newlineAddAnnotation": true
        },
        "supportAutoLanguage": [],
        "prohibitAutoAdd": [
            "json",
            "md"
        ],
        "folderBlacklist": [
            "node_modules",
            "文件夹禁止自动添加头部注释"
        ],
        "prohibitItemAutoAdd": [
            "项目的全称, 整个项目禁止自动添加头部注释, 可以使用快捷键添加"
        ],
        "moveCursor": true,
        "dateFormat": "YYYY-MM-DD HH:mm:ss",
        "atSymbol": [
            "@",
            "@"
        ],
        "atSymbolObj": {
            "文件后缀": [
                "头部注释@符号",
                "函数注释@符号"
            ]
        },
        "colon": [
            ": ",
            ": "
        ],
        "colonObj": {
            "文件后缀": [
                "头部注释冒号",
                "函数注释冒号"
            ]
        },
        "filePathColon": "路径分隔符替换",
        "showErrorMessage": true,
        "writeLog": true,
        "wideSame": true,
        "wideNum": 13,
        "functionWideNum": 0,
        "CheckFileChange": false,
        "createHeader": true,
        "useWorker": false,
        "designAddHead": false,
        "headDesignName": "random",
        "headDesign": false,
        "cursorModeInternalAll": {},
        "openFunctionParamsCheck": true,
        "functionParamsShape": [
            "{",
            "}"
        ],
        "functionBlankSpaceAll": {},
        "functionTypeSymbol": "*",
        "typeParamOrder": "type param",
        "customHasHeadEnd": {},
        "throttleTime": 60000,
        "functionParamAddStr": ":",
        "NoMatchParams": "no show param"
    },
    // 头部注释
    "fileheader.customMade": {  
        "Author": "changfei01", // 写死的固定值 不从git config中获取
        "Date": "Do not edit", // 文件创建时间(不变)
        // LastEditors、LastEditTime、FilePath将会自动更新 如果觉得时间更新的太频繁可以使用throttleTime(默认为1分钟)配置更改更新时间。
        "LastEditors": "git config user.name && git config user.email", // 文件最后编辑者 与Author字段一致
        // 由于编辑文件就会变更最后编辑时间，多人协作中合并的时候会导致merge
        // 可以将时间颗粒度改为周、或者月，这样冲突就减少很多。搜索变更时间格式: dateFormat
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        // 输出相对路径，类似: /文件夹名称/src/index.js
        "FilePath": "Do not edit", // 文件在项目中的相对路径 自动更新
        // 插件会自动将光标移动到Description选项中 方便输入 Description字段可以在specialOptions更改
        "Description": "头部注释配置模板", // 介绍文件的作用、文件的入参、出参。
    },
    // 函数注释
    "fileheader.cursorMode": {   
        "Description": "函数注释配置模板", // 函数注释生成之后，光标移动到这里
        "Param": "", // param 开启函数参数自动提取 需要将光标放在函数行或者函数上方的空白行
        "Return": "",
    }
}

```js
// 配置填在这里面
```

### 文件后缀(必填):
.go

### 你得到的注释(必填):

你生成的注释为：
fileHeader: watchSaveFn: message: ENOENT: no such file or directory, stat '/Users/changfei01/Library/Application Support/iCoding/User/settings.json'
stack: Error: ENOENT: no such file or directory, stat '/Users/changfei01/Library/Application Support/iCoding/User/settings.json'
        at Object.statSync (node:fs:1538:3)
        at noEditorValue (/home/changfei01/.vscode-server/extensions/obkoro1.korofileheader-4.9.1/src/logic/logic.js:165:25)
        at changeDataOptionFn (/home/changfei01/.vscode-server/extensions/obkoro1.korofileheader-4.9.1/src/logic/logic.js:152:10)
        at Object.userSet (/home/changfei01/.vscode-server/extensions/obkoro1.korofileheader-4.9.1/src/logic/logic.js:42:10)
        at Object.saveReplaceTime (/home/changfei01/.vscode-server/extensions/obkoro1.korofileheader-4.9.1/src/models/checkFile.js:30:22)
        at documentSaveFn (/home/changfei01/.vscode-server/extensions/obkoro1.korofileheader-4.9.1/src/models/fileSave.js:74:51)
        at /home/changfei01/.vscode-server/extensions/obkoro1.korofileheader-4.9.1/src/utile/util.js:27:7
        at /home/changfei01/.vscode-server/extensions/obkoro1.korofileheader-4.9.1/src/models/fileSave.js:62:8
        at P.i (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:96:33615)
        at P.h (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:96:32941)
        at P.$participateInSave (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:96:32738)
        at u.P (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:106:11444)
        at u.O (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:106:11162)
        at u.J (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:106:10173)
        at u.I (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:106:9074)
        at /home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:106:7812
        at f.invoke (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
        at g.deliver (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
        at h.fire (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
        at p.fire (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
        at /home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:122:15815
        at f.invoke (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
        at g.deliver (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
        at h.fire (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
        at p.fire (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
        at t.E (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:72:18927)
        at /home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:72:16915
        at f.invoke (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
        at g.deliver (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
        at h.fire (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
        at d.acceptChunk (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:72:12592)
        at /home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:72:11879
        at Socket.t (/home/changfei01/.vscode-server/bin/1.8.401.75.1.02/out/vs/workbench/api/node/extensionHostProcess.js:72:22415)
        at Socket.emit (node:events:526:28)
        at addChunk (node:internal/streams/readable:315:12)
        at readableAddChunk (node:internal/streams/readable:289:9)
        at Socket.Readable.push (node:internal/streams/readable:228:10)
        at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

也可以贴上截图：

### 预期的行为(必填)：

预期得到的注释/行为：
能够正常使用函数注释

也可以贴上截图：

### 屏幕截图(选填)

如果方便的话，添加截图来帮助解释你的问题：

### 问题相关(选填)
在这里添加关于这个问题的任何其他上下文。

#### 错误日志(选填):

[怎么生成错误日志?](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97)

**Comment by chf041** [comment]
![64084d083b1983fe503045793e9807de](https://user-images.githubusercontent.com/7721423/230333088-588113b0-0455-4663-b720-6f4b8df81a7e.png)
